blank_issues_enabled: false
contact_links:
  - name: 提问
    url: https://github.com/LoyeJun/ClassBroom/discussions/new?category=%E6%8F%90%E9%97%AE
    about: 我想问一些 PCL 相关的问题……
  - name: 讨论
    url: https://github.com/LoyeJun/ClassBroom/discussions/new?category=%E8%AE%A8%E8%AE%BA
    about: 我想讨论一些 PCL 相关的事情……
